### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by voxik** [bricestacey/ruby-zoom#2]
Hi,

Is there any chance to see your changes released as a official gem? Have you tried to contact original author. I would really appreciated to see the gem version. Thank you.

Vit

**Comment by mvz** [comment]
Hi @bricestacey it looks like the ownership issue was resolved, but the latest zoom version is still from 2007. Any chance of an updated version being released?

**Comment by bricestacey** [comment]
Definitely. I completely lost track of the whole thing. It's been several years since working in a library and I don't even write ruby anymore, but I was successfully able to install YAZ and test it out and it seems to still be working. The needle sample isn't working for me, but I am not sure if it ever worked.

I'd like to spend a little extra time reviewing the combined changes to see if it requires a bump of its major version. If you have any opinions re/ version number, please let me know.

**Comment by bricestacey** [comment]
@mvz I've gone ahead and bumped the version to 0.5.0 a
